name: flutter_nitrite
description: A Nitrite database wrapper for flutter apps.
version: 0.0.1
author: Olalekan Oladipupo<me@olalekanoladipupo.com>
homepage: https://github.com/lakexyde/flutter_nitrite.git

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.lakex.flutternitrite
    pluginClass: FlutterNitritePlugin
